# Docker Compose for Bank Statement Analyzer
# Production-ready configuration

version: '3.8'

services:
  # FastAPI Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_statement_api
    ports:
      - "${API_PORT:-8001}:8001"
    environment:
      # Database
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-bank_statements}
      
      # AWS S3
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET:-bank-statements-1761407671}
      
      # Application
      - ENV=${ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bank_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/api/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: bank_pdf_db
    environment:
      - POSTGRES_DB=${DB_NAME:-bank_statements}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=en_US.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - bank_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-bank_statements}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # LocalStack (for S3 local development - optional)
  # Uncomment if you want to test S3 locally instead of using AWS
  # localstack:
  #   image: localstack/localstack:latest
  #   container_name: bank_localstack
  #   ports:
  #     - "4566:4566"
  #   environment:
  #     - SERVICES=s3
  #     - DEFAULT_REGION=ap-southeast-1
  #     - DATA_DIR=/tmp/localstack/data
  #   volumes:
  #     - localstack_data:/tmp/localstack
  #   networks:
  #     - bank_network
  #   restart: unless-stopped

networks:
  bank_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  # localstack_data:
  #   driver: local
